# For more information about Dependabot please refer to the GitHub documentation at: https://docs.github.com/en/github/administering-a-repository/keeping-your-dependencies-updated-automatically

version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
